Fix -Wundefined-bool-conversion compile failure of master branch
Master build fails with: lib/common/Timer.cpp:171:10: error: reference cannot
be bound to dereferenced null pointer in well-defined C++ code; pointer may be
assumed to always convert to true [-Werror,-Wundefined-bool-conversion].

Also remove unused code from Timers.

(cherry picked from commit a631c82882b039f8467a2ef9abeb343f2ec5b3da)