Fix -Wundefined-bool-conversion compile failure of master branch
Master build fails with: lib/common/Timer.cpp:171:10: error: reference cannot
be bound to dereferenced null pointer in well-defined C++ code; pointer may be
assumed to always convert to true [-Werror,-Wundefined-bool-conversion].

Cannot get regtests to pass on this feature branch without fixing this.

Also remove unused code from Timers.