Attempt to fix Win64 builds on AppVeyor
While we appear to be building for Win64, VSS is not working, and this appears
to be caused by using a 32-bit compiled binary on 64-bit Windows.

This requires us to upgrade to Visual Studio 14 2015 at the same time, as
64-bit builds don't appear to work with Visual Studio 11 2012 Win64. We get the
error: "Generator Visual Studio 11 2012 Win64 given toolset specification
host=x64 that contains invalid field 'host=x64'."